# Generated by Django 2.1.5 on 2019-03-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20190326_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owns',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='owns',
            name='user',
        ),
        migrations.RemoveField(
            model_name='animalmovement',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='usermovement',
            name='distance',
        ),
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalmovement',
            name='steps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermovement',
            name='steps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.Species'),
        ),
        migrations.DeleteModel(
            name='Owns',
        ),
    ]
