# Generated by Django 2.1.5 on 2019-03-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20190327_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.Animal'),
        ),
    ]
