# Generated by Django 2.1.5 on 2019-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_user_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='intro',
            field=models.TextField(default='should add animal intro here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='static_url',
            field=models.CharField(default='static/', max_length=128),
            preserve_default=False,
        ),
    ]
